# Generated by Django 3.2 on 2021-05-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speaker', '0002_auto_20210503_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrases',
            name='audio',
            field=models.CharField(max_length=150),
        ),
    ]
